name: stepstack

services:

  stepstack-api:
    build:
      context: ./stepstack/app
    container_name: stepstack-api
    restart: unless-stopped
    ports:
      - "${API_PORT:-5000}:5000"
    environment:
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: stepstack
      INFLUX_BUCKET: steps
      GRAFANA_PORT: ${GRAFANA_PORT:-3000}
    depends_on:
      - influxdb
    networks:
      - stepstack-network

  influxdb:
    image: influxdb:2.7
    container_name: stepstack-influxdb
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: stepstack
      DOCKER_INFLUXDB_INIT_BUCKET: steps
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
    networks:
      - stepstack-network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: stepstack-grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      INFLUX_TOKEN: ${INFLUX_TOKEN}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb
    networks:
      - stepstack-network

volumes:
  influxdb_data:
    name: stepstack_influxdb_data

  grafana_data:
    name: stepstack_grafana_data

networks:
  stepstack-network:
    name: stepstack_network