apiVersion: 1

datasources:
  - name: InfluxDB-StepStack
    uid: stepstack-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true

    jsonData:
      version: Flux
      organization: stepstack
      defaultBucket: steps

    secureJsonData:
      token: ${INFLUX_TOKEN}