services:
  stepsy-api:
    build:
      context: ./app
    container_name: stepsy-api
    restart: unless-stopped
    environment:
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: stepsy
      INFLUX_BUCKET: steps
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true